name: Packaging Test

on:
  push:
    branches:
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:

env:
  SOURCE_DIR: ./
  ARTIFACTS_DIR: debian/build/release/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        DEBIAN_FRONTEND: "noninteractive"
    - name: Remove github artefacts
      run: |
        rm -rf .github/
    - name: Adjust distibution in changelog file
      run: |
        sed -i '0,/restricted/s//stable/' debian/changelog
    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
#      uses: pi-top/action-debian-package@v4
      with:
#        source_directory: "${SOURCE_DIR}"
#        artifacts_directory: "${ARTIFACTS_DIR}"
        artifacts_directory: debian/build/release/
#        target_architectures: "amd64,i386"
#        distribution: 'stable'
#        os: 'debian'
