name: Build Packages

on:
  release:
    types: [published, created, edited]

env:
  SOURCE_DIR: ./
  ARTIFACTS_DIR: debian/build/release/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        DEBIAN_FRONTEND: "noninteractive"
    - name: Remove github artefacts
      run: |
        rm -rf .github/
    - name: Adjust distibution in changelog file
      run: |
        sed -i '0,/restricted/s//stable/' debian/changelog
    - name: Build Debian package
      uses: pi-top/action-debian-package@v4
      with:
        artifacts_directory: debian/build/release/
        target_architectures: "amd64,i386"
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: debian/build/release/*
