on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'debian/*' # Push events to matching debian/*, i.e. debian/1.0-2, debian/20.15.10, debian/23.20020326

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install needed packages
        run: |
          sudo apt-get update && sudo apt-get install -y dpkg-dev
      - name: Gather changelog
        run: |
          CHANGELOG="$(dpkg-parsechangelog | tail -n +8 > debian/changelog)"
          echo "${CHANGELOG}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${CHANGELOG}
          draft: false
          prerelease: false
